version: "3.5"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/myapp
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    networks:
      - demo-nestjs-network

  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - demo-nestjs-network

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - demo-nestjs-network

  redis-worker:
    image: rediscommander/redis-commander:latest
    ports:
      - 8088:8081
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - demo-nestjs-network

networks:
  demo-nestjs-network:


volumes:
  postgres_data:
  redis_data:
